[System]
DeviceType=0
; 0 : COM     , 1 : USB,      2: AUTO       
AgentSpeed=5
ThreadDelay=1
USB_Baud=400000
TargetPageSize=4096
READ_PAGE_SIZE=0x1000
Solution=1
; 0 : 425     , 1 : 430
VerifyTime=30
FormatTime=30
Embedded=9
CheckSum=1
PMctype=-1
Language=1
;SpecialBaud=460800,N,8,2
EnableKeepFlashTypeOption=1
EnableKeepFFSOption=1
EnableKeepMediaFFSOption=1
Rando=1

[Process]
IsLocalTest=1
DatabaseName=gsmpl01
MbProcess=Download
SnProcess=Download2

[Memory]
Target=0x1200000

[Release]
CustomerName=Panasonic
File1=C:\WINDOWS\Desktop\Mapping.mbf
File2=aQ99_LYH1R1_0725.mbf
File3=Q99_LYH2R3_0725.mbf
File4=None.mbf
Title=
Product=4
;     case 1 :   // Q1688
;     case 2 :   // Q1699
;     case 3 :   // Q1688F
;     case 4 :   // RIB_8188
;     case 5 :   // KOK_7258
;     case 6 :   // AudioVOX
;     case 7 :   // LOT_TS288(16+2)
;     case 8 :   // LOT_TS288(32+4)
;     case 9 :   // SKIFF_E320
MainMbf=C:\Manuals\EB-GD\SoftWare\EB-X300\0.37\040626_RA1.PAC_C037_CN0M0709_LPCL1102mf.mbf
Enable_MainMbf=1
Enable_MapMbf=1
Enable_LgpMbf=1
MapMbf=C:\Manuals\EB-GD\SoftWare\EB-X300\0.37\040626-RA1.PAC-DF0-M07.09mf.mbf
LgpMbf=C:\Manuals\EB-GD\SoftWare\EB-X300\0.37\040706-RA1.PAC-LP4-L11.04mf.mbf
DefAgentVer=1996752153


[COM PORT]

Auto_Start=0 
;  0 : false  1: true

COM01_PORT=1
COM02_PORT=2
COM03_PORT=3
COM04_PORT=-1
COM05_PORT=-1
COM06_PORT=-1
COM07_PORT=-1
COM08_PORT=-1
COM09_PORT=-1
COM10_PORT=-1
COM11_PORT=-1
COM12_PORT=-1
;COM13_PORT=13
;COM14_PORT=14
;COM15_PORT=15
;COM16_PORT=16
;COM17_PORT=17
;COM18_PORT=18
;COM19_PORT=19
;COM20_PORT=20
Auto=0
Auto1=1

[Display]
Height=397
Width=786
Top=171
Left=115
Flag=1

[FLASH TYPE]
FLASH_TYPE1=Fujitsu_84VD21194(16M+2M)
FLASH_TYPE2=Fujitsu_84VD22183(32M+4M)
FLASH_TYPE3=AMD_29DL323DT(32M+4M)
FLASH_TYPE4=Mitsubishi_M6MGB321S4TP(32M+4M)
FLASH_TYPE5=NEC_MC222243AX(32M+4M)
FLASH_TYPE6=Fujitsu_84VD21083(16M+2M)
FLASH_TYPE7=AMD_29DL163DT(16M+2M)
FLASH_TYPE8=TOSHIBA_50VSF3580(32M+8M)
FLASH_TYPE9=TOSHIBA_50VSF3680(64M+8M)
FLASH_TYPE10=Intel_28F320C3T(16M+2M)
FLASH_TYPE11=Sharp_LH28F320C3T(32M+4M)
FLASH_TYPE12=Toshiba_50VSF2580(?)
FLASH_TYPE13=AMD_41DL640G(64M+16M)
FLASH_TYPE14=TOSHIBA_50VSF3682(64M+8M)
FLASH_TYPE15=Fujitsu_84VD23280(64M+8M)
FLASH_TYPE16=TOSHIBA_50VSF5783
FLASH_TYPE17=TOSHIBA_50VPF5782
FLASH_TYPE18=SAMSUNG_KAD060300B
FLASH_TYPE19=Fujitsu_84VP24491
;FLASH_TYPE20=
;FLASH_TYPE21=
;FLASH_TYPE22=
;FLASH_TYPE23=
;FLASH_TYPE24=
;FLASH_TYPE25=
;FLASH_TYPE26=
;FLASH_TYPE27=
;FLASH_TYPE28=
;FLASH_TYPE29=
;FLASH_TYPE30=
;FLASH_TYPE31=
;FLASH_TYPE32=


;Fujitsu_84VD21194(16M+2M)          0x31
;Fujitsu_84VD22183(32M+4M)          0x32
;AMD_29DL323DT(32M+4M)              0x33
;Mitsubishi_M6MGB321S4TP(32M+4M)    0x34
;NEC_MC222243AX(32M+4M)             0x35
;Fujitsu_84VD21083(16M+2M)          0x36
;AMD_29DL163DT(16M+2M)              0x37
;TOSHIBA_50VSF3580(32M+8M)          0x38
;TOSHIBA_50VSF3680(64M+8M)          0x39
;Intel_28F320C3T(16M+2M)            0x3A
;Sharp_LH28F320C3T(32M+4M)          0x3B
;Toshiba_50VSF2580(?)               0x3C
;AMD_41DL640G(64M+16M)              0x3D
;FTOSHIBA_50VSF3682(64M+8M)         0x3E
;Fujitsu_84VD23280(64M+8M)          0x3F
;TOSHIBA_50VSF5783                  0x40
;TOSHIBA_50VPF5782                  0x41
;SAMSUNG_KAD060300B                 0x42
;Fujitsu_84VP24491                  0x43
