[System]
DeviceType=2
; 0 : COM     , 1 : USB,      2: AUTO
AgentSpeed=5
ThreadDelay=2
USB_Baud=400000
TargetPageSize=4096
READ_PAGE_SIZE=0x1000
Solution=1
; 0 : 425     , 1 : 430
VerifyTime=500
FormatTime=30
Embedded=9
CheckSum=1
PMctype=-1
Language=1
EnableKeepFlashTypeOption=1
EnableKeepFFSOption=1
EnableKeepMediaFFSOption=1
ComCheck=1
[Process]
IsLocalTest=1
DatabaseName=gsmpl01
MbProcess=Download
SnProcess=Download2
[Memory]
Target=0x1200000
[Release]
CustomerName=Panasonic
File1=F:\test1_m.mbf
File2=aQ99_LYH1R1_0725.mbf
File3=Q99_LYH2R3_0725.mbf
File4=None.mbf
Title=VE2
Product=4
;     case 1 :   // Q1688
;     case 2 :   // Q1699
;     case 3 :   // Q1688F
;     case 4 :   // RIB_8188
;     case 5 :   // KOK_7258
;     case 6 :   // AudioVOX
;     case 7 :   // LOT_TS288(16+2)
;     case 8 :   // LOT_TS288(32+4)
;     case 9 :   // SKIFF_E320
MappingOnly=0
EnableMapping=0
; Display & Enable Mapping Selection
MappingName1=China Mapping
;Display Item, 1~9
Mapping1=Mapping_China_020709-DG1.MIC-086.00.02.mot
MainMbf=
MapnMbf=G:\main.mbf
LgpMbf=
MapMbf=
Enable_MainMbf=0
Enable_MapMbf=1
Enable_LgpMbf=0
;Mapping MOT file name, 1~9
[COM PORT]
Auto_Start=0
;  0 : false  1: true
COM01_PORT=1
COM02_PORT=2
COM03_PORT=3
COM04_PORT=-1
COM05_PORT=-1
COM06_PORT=-1
COM07_PORT=-1
COM08_PORT=-1
COM09_PORT=-1
COM10_PORT=-1
COM11_PORT=-1
COM12_PORT=-1
COM13_PORT=-1
COM14_PORT=-1
COM15_PORT=-1
COM16_PORT=-1
Auto=0
Auto1=1
[Display]
Height=544
Width=649
Top=37
Left=57
Flag=1
[Mapping]
MappingVerCheck=1
